"""Codex 站点管理命令使用的常量。"""

APPHUB_CREATE_SITE_URL_DEFAULT = "https://www.taukeytest.com/test111"
APPHUB_CREATE_SITE_URL_ENV = "OPSCLI_APPHUB_CREATE_SITE_URL"
APP_TARGET_REPO_URL_DEFAULT = "http://10.1.13.143:3000/aukeys-admin/apphub.git"
APP_TARGET_REPO_URL_ENV = "OPSCLI_APP_REPO_URL"
APP_TEMPLATE_REPO_DEFAULT = "https://gitlab.aukeyit.com/polaris/codex-custom-sites.git"
APP_TEMPLATE_REPO_ENV = "OPSCLI_APP_TEMPLATE_REPO"
APP_TEMPLATE_BRANCH_DEFAULT = "template"
APP_TEMPLATE_BRANCH_ENV = "OPSCLI_APP_TEMPLATE_BRANCH"
BINDING_SCHEMA_VERSION = 1
BINDING_RELATIVE_PATH = ".opscli/app.json"
GIT_DEFAULT_BRANCH = "main"
GIT_MIN_VERSION = (2, 30, 0)
MESSAGE_MAX_LENGTH = 512
